const SPOTIFY_CLIENT_SECRET = import.meta.env.VITE_SPOTIFY_CLIENT_SECRET;
const SPOTIFY_CLIENT_ID = import.meta.env.VITE_SPOTIFY_CLIENT_ID;
const SPOTIFY_TOKEN_URL = import.meta.env.VITE_SPOTIFY_TOKEN_URL;
const SPOTIFY_API_URL = import.meta.env.VITE_SPOTIFY_API_URL;
console.log(
	SPOTIFY_API_URL,
	SPOTIFY_CLIENT_SECRET,
	SPOTIFY_CLIENT_ID,
	SPOTIFY_TOKEN_URL
);
